### ISSUE TITLE
pip shows wrong description

### ISSUE THREAD

**Issue by hmijail** [ethereum/eth-bloom#32]
* Version: 1.0.3
* Python: 3.x
* OS: osx

### What was wrong?
Pip lists eth-bloom like this:
`eth-bloom (1.0.3)                    - Python implementation of the Ethereum Trie structure`

### What did you expect it to do?
It should mention bloom filters instead of tries.

#### Code to reproduce the error
`pip3 search eth-bloom`

**Comment by pipermerriam** [comment]
this can be fixed by updating this line in the `setup.py`

https://github.com/ethereum/eth-bloom/blob/2de0b635a0b0acc16cf44199350ab61f7ff99cec/setup.py#L35
