### ISSUE TITLE
setuptools-markdown is deprecated

### ISSUE THREAD

**Issue by RaitoBezarius** [ethereum/eth-bloom#37]
Hi there,

### What was wrong?

Since PyPI supports natively Markdown, `setuptools-markdown` has been marked deprecated.

### What did you expect it to do?

Usage of https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/

**Comment by fselmo** [comment]
closed by [this commit](https://github.com/ethereum/eth-bloom/commit/631fd0cba5164fa7a0a8369ccdaab2077cf5338a)
