### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [ethereum/eth-bloom#5]
* Version: na
* Python: all
* OS: all

### What was wrong?

Documentation of this repository is a little sparse.  While the installation/use instructions are good, there's no mention in the README or otherwise of exactly what *is* the ethereum bloom filter, what a bloom filter is, or anything.

### What did you expect it to do?

A link to the respective whitepaper(god knows there's enough of those in the ethereum world), or some kind of reference to exactly why this repository exists and what it's used for beyond code examples.

How close is this?

> Bloom filters are a type of data structure that use cryptographic hashes
to help data stored within them to be retrieved or stored.  They work like other
data structures, but in a probabilistic way: it allows for false positive
matches but not false negative matches.  Bloom filters storage space use is
low relative to other kinds of data structures.
> ( For more information on Bloom filters, see Wikipedia: https://en.wikipedia.org/wiki/Bloom_filter )

> A trie is an a kind of tree data structure for use with dynamic data

> Ethereum bloom filters are bloom filters implemented using a "trie" data
structure and the SHA-256 ("keccak") cryptographic hash function.

> To see the bloom filter used in the context of the full description of Ethereum / the "Yellow Paper" see

> DR. GAVIN WOOD - ETHEREUM: A SECURE DECENTRALISED GENERALISED TRANSACTION LEDGER, EIP-150 REVISION, FOUNDER, ETHEREUM & ETHCORE, GAVIN@ETHCORE.IO
http://gavwood.com/Paper.pdf

**Comment by pipermerriam** [comment]
If you'd like to write this up I'd be happy to get it merged.

**Comment by palash25** [comment]
If @themusicgod1 isn't working on this I would like to give it try maybe I can send a PR in a day or 2

cc @pipermerriam

**Comment by pipermerriam** [comment]
@palash25 go for it.

**Comment by pipermerriam** [comment]
Actually, now that I look, I went ahead and merged #7 .  I'm not sure what other documentation deficiencies there are, but if you think there are some go for it.

**Comment by palash25** [comment]
@pipermerriam I'll research a bit more about eth-bloom see if I can find some additional info that might be relevant to this repo. If there is nothing more to add then I will let you know and we can close this. In the meantime, I will look for other issues to work on.

**Comment by fselmo** [comment]
closing as stale
