### ISSUE TITLE
python 3.6 support

### ISSUE THREAD

**Issue by ghost** [ethereum/eth-bloom#8]
* Version: 0.5.2
* Python: <-- this
* OS: ubuntu/debian gnu/linux

### What was wrong?

both the tox.ini file and setup.py explicitly note support for python 3.4 3.5 (which was available in debian/ubuntu until recently, so it works now, but won't in the future) but not 3.6 (which will be standard in the future).

### What did you expect it to do?

work in environments where the only python interpreter is 3.6+

#### Code to reproduce the error

tox

**Comment by pipermerriam** [comment]
Yes, 3.6 should be supported.  We just need to add it.  If you are willing to make the modifications to the `.travis.yml` and `tox.ini` file I'll get it merged assumign tests pass.

**Comment by ghost** [comment]
making pr now...
